spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    url: jdbc:mysql://localhost:3306/ufc?useSSL=false
    #    url: jdbc:mysql://localhost:3306/ufc2?allowPublicKeyRetrieval=true&useSSL=false
    url: jdbc:mysql://localhost:3306/ufc?allowPublicKeyRetrieval=true&useSSL=false
    password: '123456789'
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
#      ddl-auto: create
server:
  contextPath: /ufc
  #  port: 8080
  port: 9004


logging:
  file:
    path: /
    name: ufc.log.txt
  level:
    com:
      appsdeveloperblog: debug
