#server:
#  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    url: jdbc:mysql://localhost:3306/ufc?useSSL=false
    url: jdbc:mysql://localhost:3306/ufc2?allowPublicKeyRetrieval=true&useSSL=false

    password: '123456789'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
#      ddl-auto: create
server:
  contextPath: /ufc
  port: 8080